baseURL = 'https://rubehickscube.com'
languageCode = 'en-us'
title = 'RubeHicksCube'

theme = "github-style"
googleAnalytics = "G-YLK8Y70EDK"
pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
  author = "Colter"
  description = "IT Support Technician"
  github = "RubeHicksCube"
  facebook = "RubeHixCube"
  twitter = "RubeHicksCube"
  linkedin = "ColterHicks"
  instagram = "rubehickscube"
  email = "info@colterhicks.com"
  url = "https://colterhicks.com"
  resume = "/files/Andrew Hicks Resume Public.pdf"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/HyperCubeIcon.png"
  location = "US"
  disqusShortname = "rubehickscube"

  [[params.links]]
    title = "Link"
    href = "https://colterhicks.com"
    icon = "/images/HyperCubeIcon.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]