baseURL = 'https://rubehickscube.com/'
languageCode = 'en-us'
title = 'A Site For Myself!'

theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Colter"
  description = "A Colter Site"
  github = "RubeHicksCube"
  facebook = "RubeHixCube"
  twitter = "RubeHicksCube"
  linkedin = "ColterHicks"
  instagram = "rubehickscube"
  email = "info@colterhicks.com"
  url = "https://colterhicks.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/me.jpg"
  location = "US"

  [[params.links]]
    title = "Link"
    href = "https://github.com/rubehickscube"
  [[params.links]]
    title = "Link2"
    href = "https://colterhicks.com"
    icon = "https://colterhicks.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]